#### Consider the below code to answer further questions:

In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [3]:
list_

['1', '2', '3', '4', '5']

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [5]:
### Yes Difference in datatype of list_ and array_list

In [14]:
type(list_) ## list_ is a list datatype

list

In [15]:
type(array_list) ### array_list is a numpy array

numpy.ndarray

#### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [18]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [19]:
array_list.dtype

dtype('<U1')

In [21]:
array_list.size

5

In [22]:
for i in range(array_list.size):
    print(type(array_list[i]))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#### Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
#### Will there be any difference in the data type of the elements present in both the variables, list_ and
#### array_list? If so then print the data types of each and every element present in both the variables, list_
#### and array_list.

In [23]:
array_list = np.array(object = list_, dtype = int)

In [24]:
array_list

array([1, 2, 3, 4, 5])

In [25]:
### Yes there will be difference in the datatype of elements

In [26]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [27]:
for i in range(array_list.size):
    print(type(array_list[i]))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [28]:
array_list.dtype

dtype('int64')

### Consider the below code to answer further questions:

In [29]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [30]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [31]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

#### Q4. Write a code to find the following characteristics of variable, num_array:
1. shape
2. size

In [32]:
num_array.shape

(2, 3)

In [33]:
num_array.size

6

#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [34]:
arr_zeros=np.zeros((3,3))

In [35]:
arr_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [38]:
identity_matirix=np.eye(5,5)

In [39]:
identity_matirix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])